image: maven:3.9.10-eclipse-temurin-24-alpine

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository" # absolute path to local repository, will be used to installe xternal libs
  SPRING_PROFILES_ACTIVE: test

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - integration-test
  - package
  - image
  - image-run

cache:            # jobs that use the same cache don’t have to download the files again
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_SLUG" # all commits from the same branch will share the cache

# build du projet
build-job:
  stage: build
  script:
    - |
      mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
      -Dspring.profiles.active=test \
      clean compile \
      --batch-mode --errors --fail-at-end --show-version

# tests unitaires
test-job:
  stage: test
  script:
    - mvn clean test

# Tests d'Intégration avec Testcontainers
integration-job:
  stage: integration-test
  # besoin de DinD pour Testcontainers
  services:
    - docker:dind
  variables:
    # permettre à Testcontainers de contacter le daemon Docker de GitLab
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    # Oexécuter les *IT.java avec mvn verify et croiser les doigts
    - mvn verify --batch-mode

# création du JAR
package-job: 
  stage: package
  script:
    - mvn clean package --batch-mode --fail-at-end
  artifacts:
    paths:
      - target/*.jar
    name: "microservice-notes-jar-artifacts"

# build de l'image Docker
# le job tourne dans un conteneur avec Docker CLI
image-job: 
  stage: image
  image: docker:latest
  # récupérer le JAR issu du package-job
  dependencies:
  - package-job
  # fournit le daemon Docker qui exécute les conteneurs générés par les commandes des jobs
  services:
    - docker:dind
  # objectif : tester si le Dockerfile est correct / l’image peut être créée
  # echo pour transmettre le token Docker Hub au processus docker login
  before_script: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script: 
    - docker build -t divineion/microservice-notes:$CI_COMMIT_REF_SLUG .
    - docker push divineion/microservice-notes:$CI_COMMIT_REF_SLUG

image-run-job: 
# pointer vers le daemon Docker dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
  - docker:dind
  stage: image-run
  dependencies:
    - image-job
  before_script: apk add --no-cache docker-cli 
  script: 
# lancer le conteneur en mode détaché pour libérer le terminal
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull divineion/microservice-notes:$CI_COMMIT_REF_SLUG
    - docker network create notes-test-network
    - docker run -d --name notes-test-database --network notes-test-network mongo:6.0
    - |
      docker run -d --name notes-container --rm \
      --network notes-test-network \
      -e SPRING_PROFILES_ACTIVE=test \
      -e SPRING_DATA_MONGODB_URI=mongodb://notes-test-database:27017/testdb \
      divineion/microservice-notes:$CI_COMMIT_REF_SLUG
    - docker ps
    - docker logs notes-container
    - docker stop notes-container 
